# Pipeline to deploy Python application using Windows self-hosted agent
# Pipeline triggers when a change is pushed to main or develop branches
# Step 1 - flake8 linting and testing with pytest
# Step 2 - Build Docker image
# Step 3 - Push Docker image to DockerHub
# Step 4 - Continuous Deployment of Docker image from DockerHub to render.com using render.com webhook
# configure self-hosted agent: https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/windows-agent?view=azure-devops#download-and-configure-the-agent
# Install Python in self-hosted agent: https://learn.microsoft.com/en-gb/azure/devops/pipelines/tasks/reference/use-python-version-v0?view=azure-pipelines&viewFallbackFrom=azure-devops#how-can-i-configure-a-self-hosted-agent-to-use-this-task


trigger:
  branches:
    include:
    - main
    - develop

pool:
  name: self_hosted_agent

variables:
- group: CAL_VARIABLE_GROUP

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
  displayName: 'Use Python 3.9'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install flake8
    flake8
  displayName: Flake8
  enabled: true
  continueOnError: true

- script: |
    pip install pytest
    python -m pytest
  displayName: 'pytest'

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/test-results.xml'
  inputs:
    testResultsFiles: '**/test-results.xml'
    testRunTitle: 'Python 3.9'

- task: Docker@0
  displayName: 'Build an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'docker_hub_service_connection'
    imageName: '$(DOCKERHUB_REPO):$(Build.BuildId)'
    includeLatestTag: true

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'docker_hub_service_connection'
    action: 'Push an image'
    imageName: '$(DOCKERHUB_REPO):$(Build.BuildId)'
    includeLatestTag: true

- script: |
    curl.exe $(RENDER_WEBHOOK)
  displayName: 'Deploy To render.com'
